### PR TITLE
Import questions from other session

### PR DESCRIPTION
**Pull request by Taces**
Added ability to import questions from my session A into my session B.
Might be useful if e.g. a teacher has the same lecture every semester, but as there is a new moodle course for each semester a new ARSnova session has to be created every time. With this feature questions can be imported from one session into another one (also multiple questions at once) which is way easier than creating every question from scratch again and again.
Or to create kind of a "Question pool session" where all the questions are so that questions only need to be imported into new sessions.
Either way this feature should be quite useful.

It's a little bit "hacky" with the save button in the toolbar though, as it was probably not intented to be used this way.

### CODE REVIEW

**Comment by kqc-real** [comment]
:+1: This PR offers a very nice enhancement! As a power user of ARSnova, I like the idea of a "Question Pool Session" very much.

@dgerhardt  @tekay : Please code review this PR.

**Comment by tekay** [comment]
This came from our jshint job:
importquestions_1

**Comment by tekay** [comment]
Please move the opening curly brackets to the same line as the function/if/else/etc. statement.

**Comment by tekay** [comment]
Besides this, this PR looks good :)

**Comment by tekay** [comment]
One last thing: 
The new button "Importiere Frage" should be placed at the utmost right.

**Comment by Taces** [comment]
So far I think I fixed the things you mentioned.

**Comment by tekay** [comment]
There still is one error reported by jshint and there are many reported by jscs.

**Comment by Taces** [comment]
Sorry, forgot to check the code with jshint and jscs. Fixed that now.

**Comment by tekay** [comment]
No problem, we appreciate your work!
Looks fine, merging it.

Again: Thanks for your pull requests :)

**Pull request merged**
