### PR TITLE
Renamed button "Speichern" to "Frage speichern" in NewQuestionPanel

### PR DESCRIPTION
**Pull request by kathastaden**
During the usability test of ARSnova for the module "Web Engineering" we got some feedback for tweaks.
Some test persons did not realize that the current question is saved with the button "Speichern" in the upper right corner, and thought this would save all questions that were created until then. 
Therefore we decided to change this to "Frage speichern" so that it would be clear right from the start.

Please review my changes. Maybe they will be helpful: 

* created label SAVE_QUESTION
* using new label SAVE_QUESTION instead of SAVE
* resized button width

### CODE REVIEW

**Comment by commana** [comment]
Thanks for your PR! A few things come to my mind: The english translation for `SAVE_QUESTION` seems to be missing. Additionally, the label might actually be too long for smaller smartphone screens. Did you check that this is not a problem, either on a real device or with a simulator?

**Comment by kathastaden** [comment]
Thanks for the hint. I added the english translation and also checked the size of the button on my smartphone (iPhone 5S). I attached two screenshots with the button in german and english. I think it looks fine on the mobile device. What do you think?

button_mobile_english button_mobile_german

**Comment by dgerhardt** [comment]
When I increase the button's width to 115px it overlaps with the view's title. While the change works for 'MC' it causes problems with other question formats, e. g. flashcards.

arsnova-save-button-low-res-scaled

This was tested with an emulated Android 4.4, default browser, 480x800px resolution.

We could abbreviate all of the titles but IMHO we would lose more usability than we would get in this case.

**Comment by kathastaden** [comment]
Right, I didn't check the other formats. My fault. 
Maybe another idea would be to name the Button "Anlegen" and "Create" instead of "Speichern" and "Save". 
Save (Speichern) is too general, and therefore the test persons where confused. With Create (Anlegen) we would gain a more related word, because the Button to create the question also uses the word "anlegen" and "create".

**Comment by dgerhardt** [comment]
Sounds good to me.

I am currently not sure if views are shared for creation and updating of questions so there might be more work involved than just changing the translation. @commana or @agrt56 should know more about it.

**Comment by kathastaden** [comment]
I just tested the updating of a question on my local system, and my changes are only related to the creation of a question. If I edit a question, I still see the "Save" or "Speichern" Button. So I think this would be no problem.

**Comment by kathastaden** [comment]
I just changed the name of the Save-Button to "Anlegen" and "Create" instead of "Speichern" and "Save".
Furthermore I restored the Button width to 89px, maybe this one is the better solution? What do you think?

**Pull request closed without merging**
